### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jorge0136** [contextco/codebasechat#1]
What license is this code under? Is this intended to be open source? In good news your chatbot correctly states the following about it... 

Query: 
> What license is this repo using? 

GPT Response: 
> The repository's documentation does not contain a specific section labeled "License." Without this section, I cannot determine the license type directly from the provided materials. Typically, open-source projects include a license file or a dedicated section in the README file to specify the license under which the code is released. However, in this case, such information is not present in the provided documentation. ​

Thanks!

**Comment by agamble** [comment]
Thanks for the question, I've now licensed the repo under MIT.
