### ISSUE TITLE
Support for `.jsx` & `.tsx`

### ISSUE THREAD

**Issue by jorge0136** [contextco/codebasechat#2]
Within [clone.rb](https://github.com/contextco/codebasechat/blob/fdf90bf30888583fa6f045d5708d9d67353ef4a7/app/lib/clone.rb#L63C41-L63C42) there is a filter to allow a certain set of file types. Can`.jsx` & `.tsx` be added to that filter?

Thanks!

**Comment by agamble** [comment]
Added, thanks!
